### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/SparseGPs.jl#34]
Do we want to limit this package to sparse Gaussian processes or to variational GPs or non-conjugate GPs in general?

**Comment by st--** [comment]
Good point. The _contents_ of the package would cover both sparse (but conjugate) as well as variational (non-conjugate, but perhaps non-sparse) approaches.

Hm, would `SparseVariationalGPs` be more constraining ("sparse AND variational") or expanding ("anything sparse OR variational")? `SparseAndVariationalGPs` seems a bit much of a mouthful :wink:

**Comment by rossviljoen** [comment]
Maybe even just `VariationalGPs` - since that's what they'll all have in common?

**Comment by theogf** [comment]
When I started a small prototype for VI with AbstractGPs I called it ApproximateGPs : https://github.com/theogf/ApproximateGPs.jl
Maybe this would be a good name?
